"""Public API for Ralph Mode."""

from .agent_table import AgentMessage, AgentTable
from .cli import (
    cmd_batch_init,
    cmd_complete,
    cmd_context,
    cmd_disable,
    cmd_enable,
    cmd_help,
    cmd_history,
    cmd_iterate,
    cmd_memory,
    cmd_next_task,
    cmd_prompt,
    cmd_run,
    cmd_status,
    cmd_table,
    cmd_tasks,
    cmd_validate,
    cmd_verification,
    main,
)
from .constants import (
    AVAILABLE_MODELS,
    DEFAULT_MODEL,
    FALLBACK_MODEL,
    REQUIRED_SCOPE_MARKERS,
    REQUIRED_TASK_SECTIONS,
    STRICT_ROOT,
    STRICT_TASKS,
    VERSION,
    Colors,
    colors,
)
from .context import ContextManager
from .helpers import (
    _ensure_project_root,
    _find_git_root,
    _load_prompt_for_validation,
    _load_tasks_from_file,
    _missing_task_requirements,
    _validate_task_prompt,
    print_banner,
)
from .memory import MemoryStore
from .scanner import _detect_language, _parse_sarif, _quick_grep_scan, cmd_scan
from .state import RalphMode
from .tasks import TaskLibrary
from .verification import _extract_section, _extract_verification_commands, _run_verification_commands, _truncate_output

__all__ = [
    "AgentMessage",
    "AgentTable",
    "AVAILABLE_MODELS",
    "Colors",
    "ContextManager",
    "DEFAULT_MODEL",
    "FALLBACK_MODEL",
    "MemoryStore",
    "RalphMode",
    "REQUIRED_SCOPE_MARKERS",
    "REQUIRED_TASK_SECTIONS",
    "STRICT_ROOT",
    "STRICT_TASKS",
    "TaskLibrary",
    "VERSION",
    "_detect_language",
    "_ensure_project_root",
    "_extract_section",
    "_extract_verification_commands",
    "_find_git_root",
    "_load_prompt_for_validation",
    "_load_tasks_from_file",
    "_missing_task_requirements",
    "_parse_sarif",
    "_quick_grep_scan",
    "_run_verification_commands",
    "_truncate_output",
    "_validate_task_prompt",
    "cmd_batch_init",
    "cmd_complete",
    "cmd_context",
    "cmd_disable",
    "cmd_enable",
    "cmd_help",
    "cmd_history",
    "cmd_iterate",
    "cmd_memory",
    "cmd_next_task",
    "cmd_prompt",
    "cmd_run",
    "cmd_scan",
    "cmd_status",
    "cmd_table",
    "cmd_tasks",
    "cmd_validate",
    "cmd_verification",
    "colors",
    "main",
    "print_banner",
]
